//
// Created by Khalifa Almheiri on 2/24/23.
//

#ifndef CPP_MODULE_05_PRESIDENTIALPARDONFORM_HPP
#define CPP_MODULE_05_PRESIDENTIALPARDONFORM_HPP


class PresidentialPardonForm {

};


#endif //CPP_MODULE_05_PRESIDENTIALPARDONFORM_HPP
